#ifndef OPENCVSHOWWINDOW_GLOBAL_H
#define OPENCVSHOWWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENCVSHOWWINDOW_LIBRARY)
#  define OPENCVSHOWWINDOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENCVSHOWWINDOWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENCVSHOWWINDOW_GLOBAL_H
