; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG138298 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG138299 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138300 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136441 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG136442 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136443 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG139641 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG139642 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139643 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG137664 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG137665 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG137666 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG138711 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG138712 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138713 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136758 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG136759 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136760 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_QtNewWindow@@3Uqt_meta_stringdata_QtNewWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_QtNewWindow
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000006cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000005fH
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000036H
	DB	'QtNewWindow', 00H, 'saveSignal', 00H, 00H, 'title', 00H, 'c'
	DB	'ontent', 00H
	ORG $+2
?qt_meta_data_QtNewWindow@@3QBIB DD 07H			; qt_meta_data_QtNewWindow
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	02H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	0aH
	DD	0aH
	DD	03H
	DD	04H
	DD	00H
	ORG $+4
$SG137981 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+5
$SG137982 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG137983 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136124 DB	'D:\QT\5.9.2\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+13
$SG136125 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136126 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ ; QtNewWindow::metaObject
PUBLIC	?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z	; QtNewWindow::qt_metacast
PUBLIC	?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QtNewWindow::qt_metacall
PUBLIC	?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QtNewWindow::qt_static_metacall
PUBLIC	?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z	; QtNewWindow::saveSignal
PUBLIC	?staticMetaObject@QtNewWindow@@2UQMetaObject@@B	; QtNewWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??1QString@@QEAA@XZ:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__security_cookie:QWORD
_BSS	SEGMENT
?staticMetaObject@QtNewWindow@@2UQMetaObject@@B DB 030H DUP (?) ; QtNewWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+362
	DD	imagerel $unwind$?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z DD imagerel $LN5
	DD	imagerel $LN5+140
	DD	imagerel $unwind$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA DD imagerel ?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
	DD	imagerel ?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA+25
	DD	imagerel $unwind$?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
$pdata$?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA DD imagerel ?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
	DD	imagerel ?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA+25
	DD	imagerel $unwind$?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@QtNewWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@QtNewWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@QtNewWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
CONST	SEGMENT
	ORG $+4
$cppxdata$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z DD 019930522H
	DD	02H
	DD	imagerel $stateUnwindMap$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z
	DD	00H
	DD	00H
	DD	04H
	DD	imagerel $ip2state$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z
	DD	020H
	DD	00H
	DD	01H
CONST	ENDS
xdata	SEGMENT
$unwind$?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 021a01H
	DD	011011aH
$unwind$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z DD 012b19H
	DD	0a213H
	DD	imagerel __GSHandlerCheck_EH
	DD	imagerel $cppxdata$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z
	DD	042H
$stateUnwindMap$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
	DD	00H
	DD	imagerel ?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA
$ip2state$?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z DD imagerel ?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z
	DD	0ffffffffH
	DD	imagerel ?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z+43
	DD	01H
	DD	imagerel ?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z+99
	DD	00H
	DD	imagerel ?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z+111
	DD	0ffffffffH
$unwind$?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA DD 020601H
	DD	050023206H
$unwind$?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@QtNewWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@QtNewWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'QtNewWindow::staticMetaObject'', COMDAT
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 90
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_QtNewWindow@@3Uqt_meta_stringdata_QtNewWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B+8, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_meta_data_QtNewWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QtNewWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@QtNewWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@QtNewWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'QtNewWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z PROC	; QtNewWindow::saveSignal
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 127
$LN5:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
	mov	QWORD PTR $T1[rsp], -2
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 128
	mov	QWORD PTR _a$[rsp], 0
	mov	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	mov	rax, QWORD PTR _t2$[rsp]
	mov	QWORD PTR _a$[rsp+16], rax
; Line 129
	lea	r9, QWORD PTR _a$[rsp]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@QtNewWindow@@2UQMetaObject@@B ; QtNewWindow::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
	npad	1
; Line 130
	mov	rcx, QWORD PTR _t1$[rsp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	npad	1
	mov	rcx, QWORD PTR _t2$[rsp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 88					; 00000058H
	ret	0
?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z ENDP	; QtNewWindow::saveSignal
_TEXT	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA PROC ; `QtNewWindow::saveSignal'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t2$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA ENDP ; `QtNewWindow::saveSignal'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA PROC ; `QtNewWindow::saveSignal'::`1'::dtor$1
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t1$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$1@?0??saveSignal@QtNewWindow@@QEAAXVQString@@0@Z@4HA ENDP ; `QtNewWindow::saveSignal'::`1'::dtor$1
text$x	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv136 = 32
tv69 = 36
func$1 = 40
$T2 = 48
$T3 = 56
tv139 = 64
tv141 = 72
_t$4 = 80
result$5 = 88
$T6 = 96
$T7 = 112
$T8 = 120
_o$ = 144
_c$ = 152
_id$ = 160
_a$ = 168
?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QtNewWindow::qt_static_metacall
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 68
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 69
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 70
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$4[rsp], rax
; Line 72
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN6@qt_static_:
; Line 73
	lea	rax, QWORD PTR $T7[rsp]
	mov	QWORD PTR $T2[rsp], rax
	lea	rax, QWORD PTR $T8[rsp]
	mov	QWORD PTR $T3[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv139[rsp], rax
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv141[rsp], rax
	mov	r8, QWORD PTR tv139[rsp]
	mov	rdx, QWORD PTR tv141[rsp]
	mov	rcx, QWORD PTR _t$4[rsp]
	call	?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z ; QtNewWindow::saveSignal
$LN7@qt_static_:
; Line 76
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN5@qt_static_
; Line 77
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$5[rsp], rax
; Line 78
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR func$1[rsp], rax
; Line 81
	lea	rax, OFFSET FLAT:?saveSignal@QtNewWindow@@QEAAXVQString@@0@Z ; QtNewWindow::saveSignal
	mov	QWORD PTR $T6[rsp], rax
	mov	DWORD PTR $T6[rsp+8], 0
	mov	rax, QWORD PTR func$1[rsp]
	mov	rcx, QWORD PTR $T6[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN12@qt_static_
	mov	rax, QWORD PTR func$1[rsp]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN11@qt_static_
	mov	rax, QWORD PTR func$1[rsp]
	mov	ecx, DWORD PTR $T6[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN12@qt_static_
$LN11@qt_static_:
	mov	DWORD PTR tv136[rsp], 1
	jmp	SHORT $LN13@qt_static_
$LN12@qt_static_:
	mov	DWORD PTR tv136[rsp], 0
$LN13@qt_static_:
	cmp	DWORD PTR tv136[rsp], 0
	je	SHORT $LN5@qt_static_
; Line 82
	mov	rax, QWORD PTR result$5[rsp]
	mov	DWORD PTR [rax], 0
$LN5@qt_static_:
; Line 87
	add	rsp, 136				; 00000088H
	ret	0
?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QtNewWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QtNewWindow::qt_metacall
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 109
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 110
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 111
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 112
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 113
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 114
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 115
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@QtNewWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QtNewWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 116
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 117
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 118
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 119
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 120
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 123
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@QtNewWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QtNewWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z PROC		; QtNewWindow::qt_metacast
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 101
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 102
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 103
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QtNewWindow@@3Uqt_meta_stringdata_QtNewWindow_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 104
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 105
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 106
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QtNewWindow@@UEAAPEAXPEBD@Z ENDP		; QtNewWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ PROC	; QtNewWindow::metaObject
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 96
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 97
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QtNewWindow@@2UQMetaObject@@B ; QtNewWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 98
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QtNewWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; QtNewWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\5.9.2\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 133
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\workspace\file_save_haizeiwang10086\qtsearchwindow\qtsearchwindow\generatedfiles\debug\moc_qtnewwindow.cpp
; Line 133
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
